name: "bigquery_auditlog"
version: "1.0.0"

source-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  bigquery_auditlog:
    materialized: view
